# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, ... }:

{
  imports =
    [
      <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot = {
    initrd = {
      availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
      kernelModules = [ ];
    };
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
    kernel.sysctl = {
      "vm.swappiness" = 0; # SSDs don't like swappiness
    };
  };

  services.fstrim.enable = true; # SSDs like TRIM support

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/4e5b083e-1733-4cba-85dd-778e1a97cb17";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/2C21-5B3D";
      fsType = "vfat";
    };
  };

  swapDevices = [
    {
      device = "/dev/disk/by-uuid/cdfd6f5b-5731-4e97-ad03-f59834df470c";
    }
  ];

  nix.maxJobs = lib.mkDefault 12;
}
